"""initial schema

Revision ID: df2e9dfdd6c7
Revises: 
Create Date: 2026-07-29 19:41:24.822241

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models import GUID


# revision identifiers, used by Alembic.
revision: str = 'df2e9dfdd6c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_challenges',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('code_digest', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_challenges_email'), ['email'], unique=False)
        batch_op.create_index('ix_email_challenges_email_created', ['email', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('devices',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'installation_id', name='uq_devices_user_install')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('reading_id', sa.String(length=128), nullable=True),
    sa.Column('reading_snapshot_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    # No separate UniqueConstraint('id'): the primary key already guarantees
    # global uniqueness of the client UUID, and on PostgreSQL a redundant UQ
    # clashes with the PK (detected by `alembic check`).
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notes_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('device_sessions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('device_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('token_digest', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_sessions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_sessions_token_digest'), ['token_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_sessions_token_digest'))
        batch_op.drop_index(batch_op.f('ix_device_sessions_device_id'))

    op.drop_table('device_sessions')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_user_updated')
        batch_op.drop_index(batch_op.f('ix_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_notes_deleted_at'))

    op.drop_table('notes')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))

    op.drop_table('devices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('email_challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_email_challenges_email_created')
        batch_op.drop_index(batch_op.f('ix_email_challenges_email'))

    op.drop_table('email_challenges')
    # ### end Alembic commands ###
